# cat docker-compose.yml
version: '3.8'
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=userroot
      - MYSQL_DATABASE=sport_app
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  # app:
  #   depends_on:
  #     - mysqldb
  #   build: ./bezkoder-app
  #   restart: on-failure
  #   env_file: ./.env
  #   ports:
  #     - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
  #   environment:
  #     SPRING_APPLICATION_JSON: '{
  #       "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
  #       "spring.datasource.username" : "$MYSQLDB_USER",
  #       "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
  #       "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
  #       "spring.jpa.hibernate.ddl-auto" : "update"}'
  #   volumes:
  #     - .m2:/root/.m2
  #   stdin_open: true
  #   tty: true
